apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: cloud-platform-canary-app-eks
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1000Mi
    defaultRequest:
      cpu: 4m
      memory: 100Mi
    type: Container
