---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dv-example-frontend-app-dev-cert
  namespace: dv-cloudplatform-dev
spec:
  secretName: dv-example-frontend-app-dev-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - dv-example-frontend-app-dev-dev.hmpps.service.justice.gov.uk
