apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: laa-assess-non-standard-magistrate-fee-dev-crm4
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1000Mi
    defaultRequest:
      cpu: 10m
      memory: 100Mi
    type: Container
