apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test1.magistrates.judiciary.uk
  namespace: hale-platform-dev
spec:
  secretName: magistrates-test1-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - test1.magistrates.judiciary.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test1.victimscommissioner.org.uk
  namespace: hale-platform-dev
spec:
  secretName: victimscommissioner-test1-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - test1.victimscommissioner.org.uk