kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: legacy-systems-x-product-prototype-admin
  namespace: legacy-systems-x-product-prototype
subjects:
  - kind: Group
    name: "github:farsight-devs"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
