kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laa-decide-civil-legal-aid-backend-uat-admin
  namespace: laa-decide-civil-legal-aid-backend-uat
subjects:
  - kind: Group
    name: "github:laa-decide"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
