---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-launchpad-cert
  namespace: hmpps-launchpad-staging
spec:
  secretName: hmpps-launchpad-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - launchpad-home-staging.hmpps.service.justice.gov.uk
