kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laa-claim-non-standard-magistrate-fee-dev-crm4-admin
  namespace: laa-claim-non-standard-magistrate-fee-dev-crm4
subjects:
  - kind: Group
    name: "github:crm7team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
