apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: data-platform-app-legislation-drafting-helper-dev
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 3000Mi
    defaultRequest:
      cpu: 10m
      memory: 1000Mi
    type: Container
