kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bh-app-dev-admin
  namespace: bh-app-dev
subjects:
  - kind: Group
    name: "github:hmpps-sre"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
