---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bh-example-frontend-app-dev-cert
  namespace: bh-app-dev
spec:
  secretName: bh-example-frontend-app-dev-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - bh-example-frontend-app-dev-dev.hmpps.service.justice.gov.uk
