---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-prison-visit-booker-registry-cert
  namespace: visit-someone-in-prison-backend-svc-dev
spec:
  secretName: hmpps-prison-visit-booker-registry-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - hmpps-bapv-public-booker-reg-dev.prison.service.justice.gov.uk
    - hmpps-book-a-prison-visit-public-booker-registry-dev.prison.service.justice.gov.uk
