---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-visitor-registry-prod-admin
  namespace: hmpps-visitor-registry-prod
subjects:
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:book-a-prison-visit"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
