kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operations-engineering-r53-backup-prod-admin
  namespace: operations-engineering-r53-backup-prod
subjects:
  - kind: Group
    name: "github:operations-engineering"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
