kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: data-platform-app-opg-actor-search-prod-admin
  namespace: data-platform-app-opg-actor-search-prod
subjects:
  - kind: Group
    name: "github:opg-team-rich"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
