apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: one-plan-api-dev-cert
  namespace: hmpps-one-plan-dev
spec:
  secretName: one-plan-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - hmpps-one-plan-api-dev.hmpps.service.justice.gov.uk

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: one-plan-ui-dev-cert
  namespace: hmpps-one-plan-dev
spec:
  secretName: one-plan-ui-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - hmpps-one-plan-ui-dev.hmpps.service.justice.gov.uk
