apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: casetracker-justice-app-cert
  namespace: civil-appeal-case-tracker-prod
spec:
  secretName: casetracker-justice-app-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
      - casetracker.justice.gov.uk
