kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-delius-alfresco-pre-prod-admin
  namespace: hmpps-delius-alfresco-pre-prod
subjects:
  - kind: Group
    name: "github:hmpps-migration"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
