---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: prison-visits-booking-production

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: circleci
  namespace: prison-visits-booking-production
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: prison-visits-booking-production
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: circleci
  namespace: prison-visits-booking-production
rules:
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - "prometheusrules"
      - "servicemonitors"
    verbs:
      - "*"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: circleci-prometheus
  namespace: prison-visits-booking-production
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: prison-visits-booking-production
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
