format: table

ignorefile: ./config/.trivyignore.yaml

exit-code: 1

severity:
  - HIGH
  - CRITICAL

scan:
  scanners:
    - misconfing

misconfiguration:
  include-deprecated-checks: true

  scanners:
    - terraform