---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-prisoner-cell-allocation-cert
  namespace: hmpps-prisoner-cell-allocation-prod
spec:
  secretName: hmpps-prisoner-cell-allocation-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - cell-allocation-api.prison.service.justice.gov.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-change-someones-cell-cert
  namespace: hmpps-prisoner-cell-allocation-prod
spec:
  secretName: hmpps-change-someones-cell-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - change-someones-cell.prison.service.justice.gov.uk
