kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-probation-absence-management-dev-admin
  namespace: hmpps-probation-absence-management-dev
subjects:
  - kind: Group
    name: "github:manage-a-workforce"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
