apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: probation-absence-management-cert
  namespace: hmpps-probation-absence-management-dev
spec:
  secretName: probation-absence-management-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - probation-absence-management-dev.hmpps.service.justice.gov.uk
