kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: data-platform-app-hmpps-electronic-monitoring-data-platform-api-dev-admin
  namespace: data-platform-app-hmpps-electronic-monitoring-data-platform-api-dev
subjects:
  - kind: Group
    name: "github:hmpps-electronic-monitoring"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:analytics-hq"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
