kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laa-crown-court-remuneration-sandbox-admin-admin
  namespace: laa-crown-court-remuneration-sandbox-admin
subjects:
  - kind: Group
    name: "github:laa-aws-infrastructure"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
