apiVersion: v1
kind: Namespace
metadata:
  name: interventions-prototype
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HMPPS"
    cloud-platform.justice.gov.uk/slack-channel: "interventions-dev"
    cloud-platform.justice.gov.uk/application: "Gov.UK Prototype Kit"
    cloud-platform.justice.gov.uk/owner: "refer and monitor: platforms@digital.justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/interventions-prototype"
    cloud-platform.justice.gov.uk/team-name: "hmpps-interventions"
    cloud-platform.justice.gov.uk/review-after: ""
