kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: interventions-prototype-admin
  namespace: interventions-prototype
subjects:
  - kind: Group
    name: "github:hmpps-interventions"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
