---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-temporary-accommodation-dev-admin
  namespace: hmpps-temporary-accommodation-dev
subjects:
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:hmpps-temporary-accommodation"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
