---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-temporary-accommodation-dev-cert
  namespace: hmpps-temporary-accommodation-dev
spec:
  secretName: hmpps-temporary-accommodation-dev-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - temporary-accommodation-dev.hmpps.service.justice.gov.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-temporary-accommodation-api-dev-cert
  namespace: hmpps-temporary-accommodation-dev
spec:
  secretName: hmpps-temporary-accommodation-api-dev-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - temporary-accommodation-api-dev.hmpps.service.justice.gov.uk
