kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mike-test-admin
  namespace: mike-test
subjects:
  - kind: Group
    name: "github:mike-test"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
