---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-csip-api-prod-cert
  namespace: hmpps-csip-prod
spec:
  secretName: hmpps-csip-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - csip-api.hmpps.service.justice.gov.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-csip-ui-prod-cert
  namespace: hmpps-csip-prod
spec:
  secretName: hmpps-csip-ui-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - csip.hmpps.service.justice.gov.uk
