kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: raise-an-incident-admin
  namespace: raise-an-incident-dev
subjects:
  - kind: Group
    name: "github:product-support"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
