kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aaf-dev-admin
  namespace: aaf-dev
subjects:
  - kind: Group
    name: "github:webops"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
