kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grc-dev-admin
  namespace: grc-dev
subjects:
  - kind: Group
    name: "github:pet"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
