name: grafana-linter
on:
  pull_request:
    paths:
      - 'namespaces/live.cloud-platform.service.justice.gov.uk/**/dashboard-*.yaml'
      - 'namespaces/live.cloud-platform.service.justice.gov.uk/**/dashboard-*.yml'

jobs:
  grafana-linter:
    runs-on: ubuntu-latest
    env:
      GITHUB_REF: ${{ github.ref }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      AUTH_TOKEN: ${{ secrets.LINTER_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Linter
        uses: docker://ministryofjustice/grafana_linter:0.0.5
        env:
          CHECK: "linter"
            
