name: skip-file-auto-approve

on:
  pull_request:
    paths:
      - '**/APPLY_PIPELINE_SKIP_THIS_NAMESPACE'

jobs:
  commit-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_REF: ยง{{ github.ref }}
      GITHUB_REPOSITORY: ยง{{ github.event.repository.name }}
      FILE_NAME: "APPLY_PIPELINE_SKIP_THIS_NAMESPACE"
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - id: commit-check
      name: commit-check
      uses: docker://ministryofjustice/cloud-platform-commit-check:latest
    
    - name: check commit result
      run: echo ${{ steps.commit-check.outputs.approval }}
    
    - name: auto-approve success
      if: ${{ steps.commit-check.outputs.approval == 'true' }}
      id: auto-approver-pullrequest
      run: echo "This Pull Request can be auto-approved."
      
    - name: auto-approve failure
      if: ${{ steps.commit-check.outputs.approval == 'false' }}
      run: echo "This Pull Request can not be auto-approved."