---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-education-employment-cert
  namespace: hmpps-education-employment-ui-dev
spec:
  secretName: hmpps-education-employment-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - education-employment-ui-dev.hmpps.service.justice.gov.uk
